version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nextapp/
    overwrite: yes

permissions:
  - object: /home/ubuntu/nextapp/
    owner: ubuntu
    group: ubuntu
    mode: 755
Hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
  AfterInstll:
    - location: scripts/start_server.sh
